apiVersion: v1
kind: Service
metadata:
  name: codegold-mdb
  namespace: codegold
  labels:
    app: codegold-mdb
spec:
  ports:
    - port: 3306
      name: mariadb
  selector:
    app: codegold-mdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codegold-mdb
  namespace: codegold
spec:
  serviceName: codegold-mdb
  selector:
    matchLabels:
      app: codegold-mdb
  replicas: 1
  template:
    metadata:
      labels:
        app: codegold-mdb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5.6
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdbsecrets
                  key: password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdbsecrets
                  key: user-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
