apiVersion: v1
kind: Service
metadata:
  name: codegold-wp
  labels:
    app: codegold-wp
  namespace: codegold
spec:
  selector:
    app: codegold-wp
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codegold-wp
  namespace: codegold
  labels:
    app: codegold-wp
spec:
  serviceName: codegold-wp
  selector:
    matchLabels:
      app: codegold-wp
  replicas: 1
  template:
    metadata:
      labels:
        app: codegold-wp
    spec:
      containers:
      - image: wordpress:5.5-apache
        name: wordpress
        resources:
          limits:
            cpu: 1
            memory: 8Gi
          requests:
            cpu: 1
            memory: 8Gi
        env:
        - name: WORDPRESS_DB_HOST
          value: codegold-mdb.codegold:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mdbsecrets
                key: user-password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wp-data
            mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: wp-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
